apiVersion: v1
kind: ConfigMap
metadata: 
  name: intellidocs-config
  namespace: intellidocs
data:
  OLLAMA_BASE_URL: "http://ollama-service:11434"
  REDIS_HOST: "redis-service"
  REDIS_PORT: "6379"
  MLFLOW_TRACKING_URI: "http://mlflow-service:5000"
  OLLAMA_MODEL: "llama3.2"
  APP_ENV: "production"
  LOG_LEVEL: "INFO"
  LANGCHAIN_TRACKING_V2: "false"