apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlflow
  namespace: intellidocs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mlflow
  template:
    metadata:
      labels:
        app: mlflow
    spec:
      containers:
      - name: mlflow
        image: ghcr.io/mlflow/mlflow:latest
        ports:
          - containerPort: 5000
        command:
          - mlflow
          - server
          - --host=0.0.0.0
          - --port=5000
          - --backend-store-uri=/mlflow/mlflow.db
          - --default-artifact-root=/mlflow/artifacts
          - --disable-security-middleware
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"


---
apiVersion: v1
kind: Service
metadata:
  name: mlflow-service
  namespace: intellidocs
spec:
  selector:
    app: mlflow
  ports:
  - port: 5000
    targetPort: 5000