apiVersion: apps/v1
kind: Deployment
metadata:
  name: ollama
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ollama
  template:
    metadata:
      labels:
        app: ollama
    spec:
      containers:
      - name: ollama
        image: ollama/ollama:latest
        ports:
          - containerPort: 11434
        command:
          - /bin/sh
          - -c
          - "ollama serve & sleep 10 && ollama pull llama3.2 && wait"
        resources:
          requests:
            memory: "3Gi"
            cpu: "500m"
          limits:
            memory: "5Gi"
            cpu: "2000m"


---
apiVersion: v1
kind: Service
metadata:
  name: ollama-service
  namespace: intellidocs
spec:
  selector:
    app: ollama
  ports:
  - port: 11434
    targetPort: 11434